### PR TITLE
Fix various bugs, add sample data, and refactor

### LINKED ISSUE #193: People are allowed to be created with wedding prefix without created wedding
People can create a contact with a wedding even when the wedding hasn't been created, resulting in these contacts being assigned to the wedding even though the wedding technically hasn't been created

Steps to recreate: 
```
add n/Betty w/Betty's wedding
```

```
assign-wedding 4 w/Betty's wedding
```

image

### LINKED ISSUE #281: [PE-D][Tester C] [BUG] Delete Tags
# Issue
I am unable to delete this tag named "tagg". It is mentioned in the display panel that "tagg" does not exist but it does exist as seen below.

### Steps to recreate

1. Enter "add n/Alice t/taggy"
2. Enter "delete-tag t/taggy"

- Recreated with another user named "Alice" and tag "taggy"

### Suggestion
- Maybe the display message was supposed to say something like "This tag is in used. Please use "f/" to force delete the tag."

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: ahmadsyuaib/ped#4

### LINKED ISSUE #285: [PE-D][Tester C] [BUG] Creation Of Weddings
# Issue
When i add a user to the list using the add command and add a wedding using "w/wedding", it does not automatically create a wedding for me in the wedding's list and just created a wedding field.

### Steps to recreate

1. Enter "add n/Bob7 w/wedding"
2. There is no wedding named "wedding" in the wedding list

### Suggestion
Create a new wedding automatically when adding the person.

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: ahmadsyuaib/ped#5

### LINKED ISSUE #286: [PE-D][Tester B] Bug: can add person with wedding that does not exist in the system
The above screenshot is produced when executing `add n/test2 w/wedding test`, where the wedding test is not created before. This should throw an exception if it is not allowed. 
If it is allowed,  the wedding list is not updated correctly with the newly created wedding test.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: YANYAN-w/ped#4

### LINKED ISSUE #297: [PE-D][Tester C] [BUG] Unable To Add Existing Tag
# Issue
I am unable to add a new tag "tagg" to Alice who is index 18.

### Steps to recreate (assuming there is 17 names in the list and another user with tag "tagg")

1. Enter "add n/Alice"
2. Enter "tag 18 t/tagg"

- Unable to add using "t/" eventhough "tagg" exists with Bob8 as seen above

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: ahmadsyuaib/ped#9

### LINKED ISSUE #301: [PE-D][Tester A] 'delete-tag' command: Creating a 'tag' with 'add' command does not create a Tag
After creating a tag with 'add' command with this command: add n/Tester e/betsycrowe@example.com a/ABC Photo Studio p/1234567 t/Testing, unable to delete tag "Testing" as it not considered a "Tag"

Expected: Deleted "Testing" Tag.

Actual:

"Testing" is not deleted as shown above. Perhaps allow the 'add' command to produce a tag similar to how 'create-tag' achieves it?

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: QuekBingHeng/ped#6

### LINKED ISSUE #309: [PE-D][Tester A] 'list-weddings' command: 'add' command wedding prefix not added to list of weddings
After inputting this command: add n/Tester e/betsycrowe@example.com a/ABC Photo Studio p/1234567 w/Test Wedding, "Test Wedding" is not shown in the list of weddings.

Expected: "Test Wedding" shown in list of weddings.

Actual:

"Test Wedding" is not shown as seen above. Perhaps allow the 'add' command to produce a "wedding" similar to how 'create-wedding' achieves it?

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: QuekBingHeng/ped#7

### LINKED ISSUE #313: [PE-D][Tester A] 'delete-wedding' command: Creating a 'wedding' with 'add' command does not create a Wedding
After creating a wedding with 'add' command with this command: add n/Tester e/betsycrowe@example.com a/ABC Photo Studio p/1234567 w/Test Wedding, unable to delete wedding "Test Wedding" as it is not considered a "Wedding". 

Expected: Test Wedding gets deleted.

Actual:

"Test Wedding" is not deleted as shown above. Perhaps allow the 'add' command to produce a wedding similar to how 'create-wedding' achieves it?

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: QuekBingHeng/ped#8

### PR DESCRIPTION
**Pull request by dasha3412**
This PR does the following:
1. Fixes loading of tags and weddings to ensure that all `Person`, `Wedding`, and `Tag` objects in the model are the same.
2. Fixes loading of entities from storage to ensure that `taggedCount` is loaded correctly, and removes initialisation methods from `AddressBook`
3. Extract methods in loading for `JsonSerializableAddressBook` to separate logic
4. Ensures that the `Tag` command checks whether a person is already tagged, to prevent incrementing taggedCount incorrectly
5. Adds loading of `Tags`, `Weddings`, and `Tasks` to sample data
6. Fixes `Add` command to create `Tag`s and `Wedding`s input by user that are not already in system
7. Adds error handling for `Assign-wedding` command to check if any weddings provided are duplicated

❗ **NOTE:** ❗ 
6 is implemented to *create* the Weddings and Tags ***tentatively*** as it is unclear whether barring the user from adding them to a Person being created is new functionality (not sure if it is detailed in current UG/DG, and not detailed in the command format)

Fixes #193 
Fixes #281 
Fixes #285 
Fixes #286 
Fixes #297
Fixes #301 
Fixes #309 
Fixes #313

### CODE REVIEW

**Review by tingxuanp — APPROVED** [review]
Tested and LGTM

**Comment by tingxuanp** [comment]
For your note about point 6, I think its okay to create weddings and tasks that weren't created when a person is added. I guess we could add that to the UG?

**Review by HanB1n — APPROVED** [review]
LGTM

**Comment by HanB1n** [comment]
For point 6, it is definitely a bug fix because otherwise, the application will fail to start up after exiting.

**Pull request merged**
